version: "3.9"

services:
  app:
    build: .
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres_db:
        condition: service_healthy    
    

  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5