name: Backend CI/CD

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "backend/**"

jobs:
  backend-ci-cd:
    name: Backend CI (Tests + Lint)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      docker:
        image: docker:dind
        privileged: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Docker (for Testcontainers)
        run: |
          sudo systemctl start docker
          docker info

      - name: Run linter (flake8)
        run: |
          flake8 src --max-line-length=120 --exclude=__init__.py

      - name: Run tests with coverage
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          pytest --cov=src --cov-report=term-missing --cov-fail-under=90 -v
